### ISSUE TITLE
General questions and feedback

### ISSUE THREAD

**Issue by ademcan** [breez/fiatlink#16]
Hey team,

Just opened this issue to ask some questions and give feedback

1. Is Fiatlink only supposed to work for lightning wallets? If not we should also add a public wallet address support here 
https://github.com/breez/fiatlink/blob/main/FLS01/README.md?plain=1#L18

2. Quotes can only be provided for instant payments methods, it will be difficult to provide a quote and then wait hours (if not days) for a bank transfer 
https://github.com/breez/fiatlink/blob/9819acf8d6c7bbd665b3afb83e04ad8224bf66b6/FLS01/README.md?plain=1#L30C49-L30C49

3. Some automatic cancellations should be implemented indeed, a guaranteed timestamp can be added 
https://github.com/breez/fiatlink/blob/9819acf8d6c7bbd665b3afb83e04ad8224bf66b6/FLS01/README.md?plain=1#L33C80-L33C80

4. typo in the function 
https://github.com/breez/fiatlink/blob/9819acf8d6c7bbd665b3afb83e04ad8224bf66b6/FLS01/README.md?plain=1#L63

5. why is there a max amount of 1000? 
https://github.com/breez/fiatlink/blob/9819acf8d6c7bbd665b3afb83e04ad8224bf66b6/FLS01/README.md?plain=1#L138C40-L138C40

6. Keeping track of the different statuses timestamp might be useful (not only the last one)
https://github.com/breez/fiatlink/blob/9819acf8d6c7bbd665b3afb83e04ad8224bf66b6/FLS01/README.md?plain=1#L256

**Comment by kingonly** [comment]
Thanks for the feedback @ademcan 🙏
Re #1: yes, this will be primarily used by the Breez SDK, so we're looking to focus on a Lightning experience.

**Comment by aljazceru** [comment]
6. you mean having a history  of all statuses in this endpoint? because timestamp matches current status

5. the 1000 is there (not enforced in the spec anywhere) due to non-kyc limits that majority of entities participating in this spec atm have

4. fixed

3. the spec doesn't prescribe how you handle cancellations of expired orders on your side, but it does account for expiration of both quotes and orders

2. we are aware, i'll add a way to /quote call to specify if this is a quote or estimate (payment method is known there). so based on that you either get back a quote or an estimate

**Comment by ademcan** [comment]
> 6. you mean having a history  of all statuses in this endpoint? because timestamp matches current status
Yes, I think this will be beneficial to know what is happening
> 7. the 1000 is there (not enforced in the spec anywhere) due to non-kyc limits that majority of entities participating in this spec atm have
Fine with that as long as it's not hardcoded :)
> 8. fixed
> 9. the spec doesn't prescribe how you handle cancellations of expired orders on your side, but it does account for expiration of both quotes and orders
sounds good
> 10. we are aware, i'll add a way to /quote call to specify if this is a quote or estimate (payment method is known there). so based on that you either get back a quote or an estimate
cool, thanks

**Comment by TKone7** [comment]
Hey, we're also reviewing the spec at the time and this was one of our main questions: What's a quote / what's an estimate?

> we are aware, i'll add a way to /quote call to specify if this is a quote or estimate (payment method is known there). so based on that you either get back a quote or an estimate

It would make great sense to us if the provider can indicate whether the returned value is a quote or an estimate. An estimate also does not need an expiration.

I have a couple more topics but will create new issues separately.

**Comment by aljazceru** [comment]
@ademcan  @TKone7 this https://github.com/breez/fiatlink/pull/18 should address the missing things discussed above

**Comment by aljazceru** [comment]
@ademcan i think everything here was addressed, can we close this issue?

**Comment by TKone7** [comment]
It's all fine from my side.

**Comment by ademcan** [comment]
> @ademcan i think everything here was addressed, can we close this issue?

all good for me too!
