### ISSUE TITLE
Time of execution for slow fiat rails

### ISSUE THREAD

**Issue by TKone7** [breez/fiatlink#17]
With slow fiat rails we will not be able to give any binding quotes. We'd recommend to let the service provider chose to give a binding quote or just a non-binding estimate.

In our opinion [the specs here](https://github.com/breez/fiatlink/blob/21bf18f9ce5723de762039dc0aad4ffaf47e3297/FLS01/README.md?plain=1#L43C18-L43C18) are not exactly clear how to handle this case. The provider could either
- Lock price at the time of payment arrival
- Lock price at the first withdraw
- Create new price for each withdraw attempt

In any case, the user cannot verify which one was taken, since there is no absolute truth and we don't communicate any reference rate nor fee spread.

In my opinion it would make sense to leave it up to the provider to chose when to execute the order and lock the price.

**Comment by aljazceru** [comment]
@TKone7 check https://github.com/breez/fiatlink/pull/18 i think it should address your concerns

**Comment by TKone7** [comment]
Thanks @aljazceru, this greatly improves clarity over what is binding or non-binding.

In the case of a non-binding estimate, is the provider free to chose the time of execution? The current spec mention
> user withdraws the proceeds (amount based on execution at the time)

This suggests the user decides the time of execution. To be compatible with different providers I would suggest to remove this limitation and leave it up to the provider when to execute.

**Comment by aljazceru** [comment]
oh maybe its just poorly worded, execution here is meant as depending what the market prices are at the time of order execution (Which is presumed after payment is done but not really prescribed). i will remove the wording if its causing unnecessary confusion

**Comment by TKone7** [comment]
Ah, ok that's good to hear. I thought the term "the time" could be interpreted more loosely too. But it still sounded to me as the user could decide. I think removing it is a good idea.

**Comment by aljazceru** [comment]
i've removed the mention from the description of the flows, i guess i can close this issue?
