### ISSUE TITLE
Currency fields

### ISSUE THREAD

**Issue by TKone7** [breez/fiatlink#19]
I found the following snippet in the specs.
```
{
  "amount_fiat": "1000",
  ...
  "amount_sats" : 800000,
  "btc_price": 69420,
  ...
}
```

## Unit
It seems the units for fiat are full currency units like €1, CHF 1 while the bitcoin amounts are denominated in sats. However this is nowhere clearly defined. To make things easier I would suggest to use the smallest unit for both fiat and bitcoin which would be sats and cents repectively.

## Data type
In the above snippet the fiat amount is a string. I'd suggest number for all currency amounts.

**Comment by aljazceru** [comment]
oh yeah good catch, it was a bit inconsistent with strings and integers 

i think having everything denominated in the smallest units makes sense, will clarify

**Comment by aljazceru** [comment]
addressed in the existing pr https://github.com/breez/fiatlink/pull/18

**Comment by TKone7** [comment]
There is still some confusing mentions that I would fix:

```
  # client wants to spend 1000chf
  "amount_fiat": 1000,
```

Also, this implies it's in full units instead of cents. 
```
  "btc_price": 69420,
```

**Comment by aljazceru** [comment]
you are correct, i've went through the file again and now hopefully correctly formatted and commented all units
