### ISSUE TITLE
Service fees

### ISSUE THREAD

**Issue by TKone7** [breez/fiatlink#20]
I can only see the fees communicated in the payment options endpoint.

Would it not also make sense to make the fee rate part of the quote and order? On the one hand a list of orders would already contain all information about the conditions of the trade without having to lookup the quote and payment options. On the other hand a specific fee for a payment option might change in the future. In that case you lose the information under what conditions an order was executed.

**Comment by aljazceru** [comment]
@TKone7 agreed that it would make sense to return the purchase price and fees in the order. I'm wondering if it makes sense to return the fee rate or rather the fee paid, i'm more in favor of the later

**Comment by TKone7** [comment]
Yes, rather the absolute fee as this is allows you to verify the exchange rate directly.

**Comment by aljazceru** [comment]
@TKone7  i've added fee field to the order status and quote endpoint (optional on quote endpoint in case the response is an estimate) - you can check in thee same PR https://github.com/breez/fiatlink/pull/18

**Comment by TKone7** [comment]
It's a bit ambiguous what that fee is exactly. Is the `order_fee` in fiat? I would recommend so.

About this comment:
> fee taken by the provider for binding quotes

I wonder if it's not possible to return the fee taken even in the case of an non-binding estimate. If my fee rate is 1% and you want to buy for CHF 1000 then (even in an estimate) I know your fee will be CHF 10.

**Comment by aljazceru** [comment]
agreed, it also simplifies things. I changed the wording in the document to clarify this.
