### ISSUE TITLE
amount_btc vs amount_sats

### ISSUE THREAD

**Issue by Amperstrand** [breez/fiatlink#28]
Mostly, fiat_link uses amount_sats, but in some places, the amount_btc is used.

For consistancy, I think it would be best if we always used the same everywhere: either bitcoin or sats

[BTCPayserver ](https://docs.btcpayserver.org/API/Greenfield/v1/#tag/Pull-payments-(Management)) uses amount in bitcoin as a string.

[lightning-cli](https://github.com/ElementsProject/lightning/blob/master/doc/lightning-invoice.7.md#synopsis) uses sats o msats.

Fiatlink should choose one and be consistent across all api calls.

**Comment by aljazceru** [comment]
@Amperstrand thanks for flagging the issues, it was an oversight during the review process

all amounts are now unified to sats, i've updated the documentation, swagger and reexported the clients
